[package]
name = "voip_server"
version = "0.1.0"
authors = ["Victor Azadinho Miranda <18581436+ShironCat@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = "0.15"